version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  rabbitmq:
    image: eventuateio/eventuate-rabbitmq:0.3.0.RELEASE
    ports:
      - 5672:5672

  postgres:
    image: eventuateio/eventuate-postgres:$EVENTUATE_COMMON_VERSION
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate
      USE_DB_ID: ${USE_DB_ID}

  cdc-service:
    image: eventuateio/eventuate-cdc-service:$EVENTUATE_CDC_VERSION
    ports:
      - "8099:8080"
    depends_on:
      - postgres
      - rabbitmq
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_TEST_ON_BORROW: "true"
      SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      RABBITMQ_BROKER_ADDRESSES: rabbitmq
      EVENTUATELOCAL_CDC_READER_NAME: PostgresWalReader
      EVENTUATE_OUTBOX_ID: 1
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}