cdcservice:
  build: ./eventuate-tram-cdc-mysql-service
  links:
    - postgres
    - kafka
    - zookeeper
  ports:
    - "8099:8080"
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
    SPRING_DATASOURCE_USERNAME: eventuate
    SPRING_DATASOURCE_PASSWORD: eventuate
    SPRING_DATASOURCE_TEST_ON_BORROW: "true"
    SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS: 500
    EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING: 1000
    EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING: 100
    EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS: 500
    EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: ${EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID}
    SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ACTIVEMQ_URL: tcp://${DOCKER_HOST_IP}:61616
    RABBITMQ_URL: ${DOCKER_HOST_IP}
    REDIS_HOST: ${DOCKER_HOST_IP}
    REDIS_PORT: 6379
    REDIS_PARTITIONS: 2