cdcservice:
  build: ./eventuate-tram-cdc-mysql-service
  links:
    - postgres
    - kafka
    - zookeeper
    - activemq
    - rabbitmq
    - redis
  ports:
    - "8099:8080"
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
    SPRING_DATASOURCE_USERNAME: eventuate
    SPRING_DATASOURCE_PASSWORD: eventuate
    SPRING_DATASOURCE_TEST_ON_BORROW: "true"
    SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_READER_NAME: ${EVENTUATELOCAL_CDC_READER_NAME}
    SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ACTIVEMQ_URL: tcp://activemq:61616
    RABBITMQ_URL: rabbitmq
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_PARTITIONS: 2

