zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.30.0.M14
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

redis:
  image: redis:5.0.3
  ports:
    - 6379:6379

kafka:
  image: eventuateio/eventuateio-local-kafka:0.30.0.M14
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

mysql:
  build: ./mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw
