zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.30.0.RC4
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

rabbitmq:
  build: ./rabbitmq
  ports:
    - 5672:5672

mysql:
  build: ./mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw