zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.30.1.RELEASE
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

activemq:
  build: ./activemq
  ports:
    - 8161:8161
    - 61616:61616
    - 61613:61613
    - 1883:1883
    - 61614:61614

mysql:
  build: ./mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw