version: 2.1
orbs:
  eventuate-gradle-build-and-test: "eventuate_io/eventuate-gradle-build-and-test@0.1.0"
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - eventuate-gradle-build-and-test/build-and-test:
          name: build-and-test-all-mysql-binlog-kafka
          script: ./build-and-test-all-mysql-binlog-kafka.sh
      - eventuate-gradle-build-and-test/build-and-test:
          name: build-and-test-all-mysql-binlog-redis
          script: ./build-and-test-all-mysql-binlog-redis.sh
      - eventuate-gradle-build-and-test/build-and-test:
          name: build-and-test-all-postgres-wal-rabbitmq
          script: ./build-and-test-all-postgres-wal-rabbitmq.sh
      - eventuate-gradle-build-and-test/build-and-test:
          name: build-and-test-all-mssql-polling-activemq
          script: ./build-and-test-all-mssql-polling-activemq.sh
      - eventuate-gradle-build-and-test/build-and-test:
          name: deploy-artifacts
          script: ./deploy-artifacts.sh
          context:
            - publish
          requires:
            - build-and-test-all-mysql-binlog-kafka
            - build-and-test-all-mysql-binlog-redis
            - build-and-test-all-postgres-wal-rabbitmq
            - build-and-test-all-mssql-polling-activemq
